SLOT_REEL_LENGTH = 10
SLOT_ALPHABET_SIZE = 10

BUILDING_1_KEY = "building_1"
BUILDING_2_KEY = "building_2"
BUILDING_3_KEY = "building_3"
BUILDING_4_KEY = "building_4"
BUILDING_5_KEY = "building_5"
BUILDING_6_KEY = "building_6"
BUILDING_7_KEY = "building_7"
BUILDING_8_KEY = "building_8"
BUILDING_9_KEY = "building_9"
BUILDING_10_KEY = "building_10"
BUILDING_11_KEY = "building_11"
BUILDING_12_KEY = "building_12"
BUILDING_13_KEY = "building_13"

ACCOUNT_TIER_0_ID = "account_tier_0"
ACCOUNT_TIER_1_ID = "account_tier_1"
ACCOUNT_TIER_2_ID = "account_tier_2"
ACCOUNT_TIER_3_ID = "account_tier_3"
ACCOUNT_TIER_4_ID = "account_tier_4"
ACCOUNT_TIER_5_ID = "account_tier_5"
ACCOUNT_TIER_6_ID = "account_tier_6"
ACCOUNT_TIER_7_ID = "account_tier_7"
ACCOUNT_TIER_8_ID = "account_tier_8"
ACCOUNT_TIER_9_ID = "account_tier_9"

ACCOUNT_TIER_0_TOKEN_PRICE = 0
ACCOUNT_TIER_1_TOKEN_PRICE = 10
ACCOUNT_TIER_2_TOKEN_PRICE = 25
ACCOUNT_TIER_3_TOKEN_PRICE = 100
ACCOUNT_TIER_4_TOKEN_PRICE = 1000
ACCOUNT_TIER_5_TOKEN_PRICE = 10000
ACCOUNT_TIER_6_TOKEN_PRICE = 67000
ACCOUNT_TIER_7_TOKEN_PRICE = 200000
ACCOUNT_TIER_8_TOKEN_PRICE = 750000
ACCOUNT_TIER_9_TOKEN_PRICE = 3000000
